### ISSUE TITLE
LSP is probably a bad fit

### ISSUE THREAD

**Issue by isovector** [phijor/agda-mode-ng#1]
Hi all,

As author of a big interactive feature in the Haskell language server, and [cornelis](https://github.com/isovector/cornelis) (agda-mode for vim), I've been on both sides of this project and suspect LSP is a bad choice. LSP works on a model of "send every possible action to the client, and then wait to hear back" which doesn't work very well for interactive use cases. It has no support for polling the user for input (eg, case split), nor for any meaningful persistent view like the info window. It has no support for moving the cursor.

Of course, LSP is technically extensible, so you could just build your own functionality here. But then you lose the editor compatibility again, requiring all clients to implement the extensions. 

My read is that LSP is an overengineed, underspecified protocol designed for typescript use-cases, and anything that doesn't fit into a C programmer's understanding of how programming should be will necessarily be a second-class citizen.

**Comment by ashinkarov** [comment]
Thanks fro your comments.  We certainly do not insist on LSP.  However, right now this is the closest thing to the standard for asking an external tool to do stuff while editing and handling responses.  Therefore it seem to be worth while to try.  We put together some assumptions (still very rough document [here](https://github.com/phijor/agda-mode-ng/blob/main/LSP.md)), so maybe you want to comment whether something is completely off.

As for the asynchronous model, it surely becomes difficult to handle communication, as you suddenly have to talk about synchronisations.  However, fully synchronous solution sounds like a poor choice, given that Agda is really slow.  I think that it would be nice to be able to carry on editing the file after reload without screwing up all colours.

Do you have any alternatives in mind that are supported by major text editors?

**Comment by isovector** [comment]
I suppose the point I'm trying to make is that most of the functionality `adga-mode` exports is not covered by LSP, with the exception of syntax highlighting and go-to definition. The editor compatability story is missing, because for any relevant functionality, you'll need to implement it yourself in every editor as an LSP extension (or somehow persuade the LSP standardization committee).

> Do you have any alternatives in mind that are supported by major text editors?

Unfortunately I don't. An alternative approach however is to make agda's `--interaction-json` mode smarter. Right now I'd estimate it's on the order of a month of engineering time to build a feature-complete agda-mode clone. If Agda were smarter, it could do more of that work, and lower the burden for client integration to the order of a day or so.

For example, Agda's JSON interaction interface gives token info in terms of bytes from the start of the document. Vim emphatically doesn't support this, and insists on `(line, byte offset)` pairs. Wrangling the data into the right format took a day or so to iron out all of the unicode-relevant bugs. But since Agda is dumping a huge amount of information anyway, what's the harm in sending a few different notions of indexing schemes?

Similarly, supporting go-to definition requires the client to save the highlighting info somewhere. What if instead agda supported an IOTCM that said "what is the identifier at some position?" Then the client flow could be to send the curent position to Agda, get back the file path, and then jump there. Bonus points if it supports all the different indexing schemes as the hihglighting gives.

My guess is that Agda already has all of the necessary information to support these use cases; it just hasn't been exported. Furthermore, the separation between `--interaction` and `--interaction-json` is a big source of bugs, since I seem to be the only real consumer of the latter interface.

**Comment by ashinkarov** [comment]
> most of the functionality adga-mode exports is not covered by LSP

Well, in the `LSP.md` we have a list of 17 LSP Language features (part of the protocol) that we believe can be used to cover many existing interaction cases.  For example, it seems that Code lenses can be used to show information such as types and contexts; Code actions can be used to implement refine/give/casesplit; etc.  Are we fundamentally missing something?  (we didn't implement any of these, so we can be surely delusional).

> make agda's --interaction-json mode smarter

I guess we all agree here, this is something we want to achieve.  However, it would be really nice, to offload server-like concurrent behaviour to something that already exists.  In this case we can try to keep clients as dumb as possible.

Well, we are still very much in experimental mode.  We might learn after a few attempts that you are right :)

**Comment by isovector** [comment]
> Code lenses can be used to show information such as types and contexts

Every editor I've seen will give one only code lens per line, and can be only a single line tall. It's fine for eg showing the type of a top-level declaration, or a single-line refactoring option, but not much else. Furthermore, code lenses are not things you can pop up at will; they're just always there. I think you'd be very hard pressed to stick a context into one.

> Code actions can be used to implement refine/give/casesplit

This is true if you want to implement the `{! something !}` behavior and have it refine to `something`. If you have a `{! !}`, however, LSP has no support to ask you what you want to case split on.

**Comment by phijor** [comment]
Hi @isovector, I appreciate your feedback :)

> This is true if you want to implement the `{! something !}` behavior and have it refine to `something`. If you have a `{! !}`, however, LSP has no support to ask you what you want to case split on.

I think you are correct; the protocol does not (easily) allow for communication that involves back-and-forth requests. In this particular instance however, I think the functionality can be implemented in a different way.

For example, using the [Idris Language Server](https://github.com/idris-community/idris2-lsp), one can case-split on an argument by hovering over the corresponding pattern, i.e. on the LHS of a clause. This covers at least splitting explicit arguments, and can potentially be extended to implicits. This is of course different than what people are used to from `agda-mode`, but I don't think that's necessarily a bad thing. Personally, I consider *point at the pattern* more intuitive UX than *spell the pattern*.

In a way, the server pushes all interesting locations in a buffer to the client up front, instead of asking the client for (potentially outdated) information.

**Comment by isovector** [comment]
I'm going to close this issue and wish you all the best! Looking forward to what you cook up!
